### ISSUE TITLE
docker: no `latest` tag of the docker image

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.pacta#102]
When I try to run `docker compose up --build` I get the following error:
``` bash
docker: Error response from daemon: manifest for rmi-pacta/workflow.pacta not found.
```

Looking at the `docker-compose.yml` I have:
``` yaml
---
services:
  workflow.pacta:
    # build: .
    image: ghcr.io/rmi-pacta/workflow.pacta
    # stdin_open: true
    # tty: true
    # entrypoint: ["R", "--args"]
    command: '/test_params.json'
    # command: '{\"portfolio\": {\"files\": [\"default_portfolio.csv\"], \"holdingsDate\": \"2023-12-31\"}, \"inherit\": \"2023Q4\"}'
    environment:
      LOG_LEVEL: TRACE
      PACTA_DATA_DIR: "/mnt/pacta-data"
      ANALYSIS_OUTPUT_DIR: "/mnt/analysis_output_dir"
      PORTFOLIO_DIR: "/mnt/portfolios"
    volumes:
      - type: bind
        source: ${data_dir:-./pacta-data}
        target: /mnt/pacta-data
        read_only: true
      - type: bind
        source: ${analysis_output_dir:-./analysis_output_dir}
        target: /mnt/analysis_output_dir
        read_only: false
      - type: bind
        source: ${input_dir:-./portfolios}
        target: /mnt/portfolios
        read_only: true
      - type: bind
        source: ./portfolios/default_params.json
        target: /test_params.json
        read_only: true

```

When I run:
``` bash
docker pull ghcr.io/rmi-pacta/workflow.pacta
```

I get the same error, however running:
``` bash
docker pull ghcr.io/rmi-pacta/workflow.pacta:nightly
```

Works as expected. This seems to just be an issue with the image tagging (i was able to get a run working locally by adding the `nightly` tag to the image in the `docker-compose.yml`

Maybe adding a `latest` tag on `ghcr.io` would result in a default run being possible?
